apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo-deployment.yaml
  - mongo-service.yaml
  - mongo-pvc.yaml
  - registry.yaml
  - updater.yaml
  - secret.yaml
  - bot-deployment.yaml
  - hp-deployment.yaml
  - hp-service.yaml
  - hp-ingress.yaml
  - hp-hpa.yaml
  - clickhouse-deployment.yaml
  - clickhouse-service.yaml
  - clickhouse-pvc.yaml
