apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:8.0.0
          name: mongo
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-configdb
            - mountPath: /data/db
              name: mongo-db
          envFrom:
            - secretRef:
                name: mongo-secret
          env:
            - name: TZ
              value: Asia/Tokyo
      volumes:
        - persistentVolumeClaim:
            claimName: db-config
          name: mongo-configdb
        - persistentVolumeClaim:
            claimName: db-data
          name: mongo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
        - image: mongo-express:latest
          name: mongo
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: analyze-bot
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: xGJDf7f95LMh9PHFyFmZn3ig3zVyh39PKZz3ycJV
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
            - name: TZ
              value: Asia/Tokyo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-exp
  name: mongo-exp
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: mongo-exp
  type: LoadBalancer
