apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: analyze-bot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-csi"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-config
  labels:
    app: analyze-bot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-csi"
